#!/bin/sh

##############################################################################
##  Gradle start up script for POSIX generated by Gradle.
##############################################################################

APP_BASE_NAME=$(basename "$0")
APP_HOME=$(pwd)

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support.
cygwin=false; darwin=false; msys=false;
case "$(uname)" in
  CYGWIN* ) cygwin=true ;;
  Darwin* ) darwin=true ;;
  MSYS* | MINGW* ) msys=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -n "$JAVA_HOME" ] ; then
    JAVACMD=$JAVA_HOME/bin/java
else
    JAVACMD=java
fi

if ! command -v java >/dev/null 2>&1 ; then
    die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

# Increase maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" ; then
    MAX_FD=$(ulimit -H -n) || warn "Could not query maximum file descriptor limit"
    ulimit -n "$MAX_FD" || warn "Could not set maximum file descriptor limit to $MAX_FD"
fi

exec "$JAVACMD" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
